name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: sbt -v "print fullClasspath" run
